export const apiEndpoints = {
  profile: {
    method: "GET",
    url: "https://connect.garmin.com/gc-api/userprofile-service/userprofile/userProfileBase",
    keep: [
      "userProfilePk",
      "birthDate",
      "gender",
      "measurementSystemPk",
      "timeZonePk",
      "countryCode",
      "createDate",
      "displayName",
    ],
    description:
      "Returns user profile information like name, age, displayname, etc.",
  },
  predictions: {
    method: "GET",
    url: "https://connect.garmin.com/gc-api/metrics-service/metrics/racepredictions/latest/0",
    keep: ["time5K", "time10K", "timeHalfMarathon", "timeMarathon"],
    description: "Returns latest user race predictions.",
  },
  sleep: {
    method: "GET",
    url: "https://connect.garmin.com/gc-api/sleep-service/sleep/dailySleepData",
    description: "Returns sleep details for a specific date.",
    keep: [
      "dailySleepDTO.id",
      "dailySleepDTO.calendarDate",
      "dailySleepDTO.sleepTimeSeconds",
      "dailySleepDTO.sleepStartTimestampGMT",
      "dailySleepDTO.sleepEndTimestampGMT",
      "dailySleepDTO.deepSleepSeconds",
      "dailySleepDTO.lightSleepSeconds",
      "dailySleepDTO.remSleepSeconds",
      "dailySleepDTO.awakeSleepSeconds",
      "dailySleepDTO.averageSpO2Value",
      "dailySleepDTO.lowestSpO2Value",
      "dailySleepDTO.highestSpO2Value",
      "dailySleepDTO.averageRespirationValue",
      "dailySleepDTO.lowestRespirationValue",
      "dailySleepDTO.highestRespirationValue",
      "dailySleepDTO.avgSleepStress",
      "dailySleepDTO.avgHeartRate",
      "dailySleepDTO.sleepScoreFeedback",
      "dailySleepDTO.sleepScoreInsight",
      "dailySleepDTO.sleepScores.overall.value",
      "dailySleepDTO.sleepScores.totalDuration.qualifierKey",
      "dailySleepDTO.sleepScores.stress.qualifierKey",
      "dailySleepDTO.sleepScores.awakeCount.qualifierKey",
      "dailySleepDTO.sleepScores.remPercentage.value",
      "dailySleepDTO.sleepScores.lightPercentage.value",
      "dailySleepDTO.sleepScores.deepPercentage.value",
      "dailySleepDTO.sleepNeed.baseline",
      "dailySleepDTO.sleepNeed.actual",
      "dailySleepDTO.sleepNeed.feedback",
      "dailySleepDTO.breathingDisruptionSeverity",
      "dailySleepDTO.sleepAlignment.status",
    ],
    query: {
      date: {
        type: "string (YYYY-MM-DD)",
        required: true,
        description: "Date of the summary",
      },
      nonSleepBufferMinutes: {
        type: "number (min)",
        required: true,
        description: "Non sleep buffer time",
      },
    },
  },
  summary: {
    method: "GET",
    url: "https://connect.garmin.com/gc-api/usersummary-service/usersummary/daily/",
    keep: [
      "totalSteps",
      "totalDistanceMeters",
      "activeSeconds",
      "highlyActiveSeconds",
      "sedentarySeconds",
      "totalKilocalories",
      "activeKilocalories",
      "bmrKilocalories",
      "remainingKilocalories",
      "minHeartRate",
      "maxHeartRate",
      "restingHeartRate",
      "lastSevenDaysAvgRestingHeartRate",
      "averageStressLevel",
      "maxStressLevel",
      "stressPercentage",
      "lowStressPercentage",
      "mediumStressPercentage",
      "stressDuration",
      "restStressDuration",
      "activityStressDuration",
      "bodyBatteryChargedValue",
      "bodyBatteryDrainedValue",
      "bodyBatteryHighestValue",
      "bodyBatteryLowestValue",
      "bodyBatteryMostRecentValue",
      "bodyBatteryAtWakeTime",
      "sleepingSeconds",
      "measurableAsleepDuration",
      "measurableAwakeDuration",
      "avgWakingRespirationValue",
      "lowestRespirationValue",
      "highestRespirationValue",
      "averageSpo2",
      "lowestSpo2",
      "latestSpo2",
      "intensityMinutesGoal",
      "moderateIntensityMinutes",
      "vigorousIntensityMinutes",
      "stressQualifier",
      "bodyBatteryDynamicFeedbackEvent.feedbackShortType",
      "bodyBatteryActivityEventList.eventType",
      "bodyBatteryActivityEventList.activityType",
      "bodyBatteryActivityEventList.activityId"
    ],
    description:
      "Returns a summary of user's health and activity data for the day (stress, steps, battery level, etc.)",
    params: {
      displayName: {
        type: "string",
        description: "User displayName",
      },
    },
    query: {
      calendarDate: {
        type: "string (YYYY-MM-DD)",
        required: true,
        description: "Date of the summary",
      },
    },
  },
  weather: {
    method: "GET",
    url: "https://connect.garmin.com/gc-api/activity-service/activity/{activityId}/weather",
    keep: ["temp", "apparentTemp", "dewPoint", "relativeHumidity", "windSpeed"],
    description: "Returns weather details of a specific activity.",
    params: {
      activityId: {
        type: "number",
        description: "Activity ID",
      },
    },
  },
  gear: {
    method: "GET",
    url: "https://connect.garmin.com/gc-api/gear-service/gear/filterGear",
    keep: [
      "gearMakeName",
      "gearModelName",
      "gearTypeName",
      "gearStatusName",
      "displayName",
      "customMakeModel",
      "dateBegin",
    ],
    description: "Returns a list of all gears used in a specific activity.",
    query: {
      activityId: {
        type: "number",
        required: true,
        description: "Activity ID",
      },
    },
  },
  activities: {
    method: "GET",
    url: "https://connect.garmin.com/gc-api/activitylist-service/activities/search/activities",
    description: "Returns the most recent activities",
    keep: [
      "activityId",
      "activityType.typeKey",
      "startTimeGMT",
      "distance",
      "duration",
      "movingDuration",
      "averageHR",
      "maxHR",
      "elevationGain",
      "avgPower",
      "vO2MaxValue",
      "activityTrainingLoad",
      "averageSpeed",
      "avgGradeAdjustedSpeed",
      "averageRunningCadenceInStepsPerMinute",
      "avgStrideLength",
      "differenceBodyBattery",
    ],
    query: {
      limit: {
        type: "number",
        required: true,
        description: "The limit of the number of activities to return",
      },
      start: {
        type: "number",
        required: true,
        description: "",
      },
      activityType: {
        type: "string",
        required: false,
        description: "Filter by activity type (e.g., 'running')",
      },
      search: {
        type: "string",
        required: false,
        description: "Search term to filter activities by name",
      },
    },
  },
  activity_id: {
    method: "GET",
    url: "https://connect.garmin.com/gc-api/activity-service/activity/{activityId}",
    description: "Returns detailed information about a specific activity.",
    keep: [
      "activityId",
      "activityTypeDTO.typeKey",
      "activityName",

      "summaryDTO.startTimeGMT",
      "summaryDTO.startTimeLocal",
      "summaryDTO.distance",
      "summaryDTO.duration",
      "summaryDTO.movingDuration",
      "summaryDTO.elapsedDuration",
      "summaryDTO.averageSpeed",
      "summaryDTO.averageMovingSpeed",
      "summaryDTO.maxSpeed",
      "summaryDTO.avgGradeAdjustedSpeed",
      "summaryDTO.elevationGain",
      "summaryDTO.elevationLoss",
      "summaryDTO.minElevation",
      "summaryDTO.maxElevation",
      "summaryDTO.averageHR",
      "summaryDTO.maxHR",
      "summaryDTO.minHR",
      "summaryDTO.averageRunCadence",
      "summaryDTO.maxRunCadence",
      "summaryDTO.strideLength",
      "summaryDTO.groundContactTime",
      "summaryDTO.verticalOscillation",
      "summaryDTO.verticalRatio",
      "summaryDTO.averagePower",
      "summaryDTO.maxPower",
      "summaryDTO.normalizedPower",
      "summaryDTO.totalWork",
      "summaryDTO.trainingEffect",
      "summaryDTO.anaerobicTrainingEffect",
      "summaryDTO.activityTrainingLoad",
      "summaryDTO.trainingEffectLabel",
      "summaryDTO.differenceBodyBattery",
      "summaryDTO.beginPotentialStamina",
      "summaryDTO.endPotentialStamina",
      "summaryDTO.minAvailableStamina",
      "summaryDTO.calories",
      "summaryDTO.moderateIntensityMinutes",
      "summaryDTO.vigorousIntensityMinutes",
    ],
    params: {
      activityId: {
        type: "number",
        description: "Activity ID",
      },
    },
  },
  laps: {
    method: "GET",
    url: "https://connect.garmin.com/gc-api/activity-service/activity/{activityId}/laps",
    description: "Returns laps data for an activity.",
    keep: [
      "activityId",
      "lapDTOs.lapIndex",
      "lapDTOs.startTimeGMT",
      "lapDTOs.intensityType",
      "lapDTOs.distance",
      "lapDTOs.duration",
      "lapDTOs.movingDuration",
      "lapDTOs.elapsedDuration",
      "lapDTOs.averageSpeed",
      "lapDTOs.averageMovingSpeed",
      "lapDTOs.maxSpeed",
      "lapDTOs.avgGradeAdjustedSpeed",
      "lapDTOs.elevationGain",
      "lapDTOs.elevationLoss",
      "lapDTOs.minElevation",
      "lapDTOs.maxElevation",
      "lapDTOs.averageHR",
      "lapDTOs.maxHR",
      "lapDTOs.averageRunCadence",
      "lapDTOs.maxRunCadence",
      "lapDTOs.strideLength",
      "lapDTOs.groundContactTime",
      "lapDTOs.verticalOscillation",
      "lapDTOs.verticalRatio",
      "lapDTOs.averagePower",
      "lapDTOs.maxPower",
      "lapDTOs.normalizedPower",
      "lapDTOs.totalWork",
    ],

    params: {
      activityId: {
        type: "number",
        description: "Activity ID",
      },
    },
  },
};
